spring:
  datasource:
    quizbank:
      url: jdbc:mysql://47.92.132.41:3306/quizData?useUnicode=true&characterEncoding=utf8
      username: guest
      password: guest
      driver-class-name: com.mysql.cj.jdbc.Driver


    quizuser:
      url: jdbc:mysql://47.92.207.243:3306/quizUser?useUnicode=true&characterEncoding=utf8
      username: guest
      password: guest
      driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8010